import type { FeaturedModel } from "./types";

/**
 * Curated list of known-good GGUF models for offline browsing.
 * Updated with app releases. All metadata is pre-verified.
 */
export const FEATURED_MODELS: FeaturedModel[] = [
	{
		repoId: "bartowski/Qwen2.5-0.5B-Instruct-GGUF",
		filename: "Qwen2.5-0.5B-Instruct-Q4_K_M.gguf",
		displayName: "Qwen 2.5 0.5B Instruct",
		description: "Ultra-light model that works on any device. Great for quick responses.",
		fileSizeBytes: 397_000_000,
		parametersB: 0.5,
		quantization: "Q4_K_M",
		pipelineTag: "text-generation",
		sha256: "",
		downloadUrl: "https://huggingface.co/bartowski/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/Qwen2.5-0.5B-Instruct-Q4_K_M.gguf?download=true",
		contextLength: 32768,
	},
	{
		repoId: "bartowski/Llama-3.2-1B-Instruct-GGUF",
		filename: "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
		displayName: "Llama 3.2 1B Instruct",
		description: "Meta's compact model. Fast and efficient for everyday tasks.",
		fileSizeBytes: 800_000_000,
		parametersB: 1,
		quantization: "Q4_K_M",
		pipelineTag: "text-generation",
		sha256: "",
		downloadUrl: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf?download=true",
		contextLength: 131072,
	},
	{
		repoId: "bartowski/gemma-2-2b-it-GGUF",
		filename: "gemma-2-2b-it-Q4_K_M.gguf",
		displayName: "Gemma 2 2B Instruct",
		description: "Google's compact model. Strong reasoning in a small package.",
		fileSizeBytes: 1_600_000_000,
		parametersB: 2,
		quantization: "Q4_K_M",
		pipelineTag: "text-generation",
		sha256: "",
		downloadUrl: "https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q4_K_M.gguf?download=true",
		contextLength: 8192,
	},
	{
		repoId: "bartowski/Qwen2.5-3B-Instruct-GGUF",
		filename: "Qwen2.5-3B-Instruct-Q4_K_M.gguf",
		displayName: "Qwen 2.5 3B Instruct",
		description: "Sweet spot for mid-range devices. Strong reasoning and coding.",
		fileSizeBytes: 2_050_000_000,
		parametersB: 3,
		quantization: "Q4_K_M",
		pipelineTag: "text-generation",
		sha256: "",
		downloadUrl: "https://huggingface.co/bartowski/Qwen2.5-3B-Instruct-GGUF/resolve/main/Qwen2.5-3B-Instruct-Q4_K_M.gguf?download=true",
		contextLength: 32768,
	},
	{
		repoId: "bartowski/google_gemma-3-4b-it-GGUF",
		filename: "google_gemma-3-4b-it-Q4_K_M.gguf",
		displayName: "Gemma 3 4B Vision",
		description: "Google's multimodal model. Handles both text and image inputs.",
		fileSizeBytes: 2_800_000_000,
		parametersB: 4,
		quantization: "Q4_K_M",
		pipelineTag: "image-text-to-text",
		sha256: "",
		downloadUrl: "https://huggingface.co/bartowski/google_gemma-3-4b-it-GGUF/resolve/main/google_gemma-3-4b-it-Q4_K_M.gguf?download=true",
		mmprojFilename: "mmproj-google_gemma-3-4b-it-bf16.gguf",
		mmprojSizeBytes: 851_000_000,
		mmprojDownloadUrl: "https://huggingface.co/bartowski/google_gemma-3-4b-it-GGUF/resolve/main/mmproj-google_gemma-3-4b-it-bf16.gguf?download=true",
		contextLength: 8192,
	},
	{
		repoId: "leafspark/Llama-3.2-11B-Vision-Instruct-GGUF",
		filename: "Llama-3.2-11B-Vision-Instruct.Q4_K_M.gguf",
		displayName: "Llama 3.2 11B Vision",
		description: "Meta's vision-language model. Understands images and text together.",
		fileSizeBytes: 6_800_000_000,
		parametersB: 11,
		quantization: "Q4_K_M",
		pipelineTag: "image-text-to-text",
		sha256: "",
		downloadUrl: "https://huggingface.co/leafspark/Llama-3.2-11B-Vision-Instruct-GGUF/resolve/main/Llama-3.2-11B-Vision-Instruct.Q4_K_M.gguf?download=true",
		mmprojFilename: "Llama-3.2-11B-Vision-Instruct.mmproj.bf16.gguf",
		mmprojSizeBytes: 1_940_000_000,
		mmprojDownloadUrl: "https://huggingface.co/leafspark/Llama-3.2-11B-Vision-Instruct-GGUF/resolve/main/Llama-3.2-11B-Vision-Instruct.mmproj.bf16.gguf?download=true",
		contextLength: 131072,
	},
];
